branches:
  only:
    - master
    - travis
language: objective-c
install: bundle install
script: bundle exec rake spec
before_script:
  - sudo mkdir -p /Users/travis/Library/RubyMotion/build
  - sudo chmod 0777 /Users/travis/Library/RubyMotion/build
